### ISSUE TITLE
MailSync protocol study

### ISSUE THREAD

**Issue by notpushkin** [notpushkin/Mailspring-Libre#12]

**Comment by ccrvlh** [comment]
Just a small comment on this issue.
I just tried Mailspring. 

So I registered 6 accounts (not pro): 1 for my work, 2 personal, and 3 business (A, B, C).
Then, to test the calendar functionality, I send an e-mail from personal-1 (hotmail, straight from the web) to my work account. For my surprise, I received an e-mail in my work account from business-B account!!! I actually could have lost my job just by using the client... 

Just wanted to mention, here, since I don't feel Mailspring is too worried about their user base, I don't think they would do nothing about it, but when considering the "libre" version, knowing that is has the same engine makes me run away from unfortunately. I love the UI, how it feels, the themes and everything, but I just can't trust the most basic aspect of the application. I would recommend you to keep the UI and choose some other engine.

Thanks a lot for the project!
Best

**Comment by ccrvlh** [comment]
BTW, would it be possible to use Nylas API as an engine? I make use of the front end only?

**Comment by ccrvlh** [comment]
https://github.com/closeio/sync-engine
Seems like some devs are still keeping the sync engine from Nylas.

**Comment by notpushkin** [comment]
I believe MailSync should probably be pretty close to Nylas API protocol-wise, and if it is so, it could be easy to adapt (not a drop-in replacement, but might be actually pretty close).

**Comment by aquelehugo** [comment]
Mailsync is now opensource and there is a plan on making Mailspring ID optional:
https://github.com/Foundry376/Mailspring/issues/33#issuecomment-775331676

**Comment by Lcchy** [comment]
That's pretty cool! They are saying that it's going to be optional this year which could mean a few months. How hard do you think it would be to disable the login prompt and the mailspring server sync manually?
I am going to have a look but I'm new to the codebase :)
