### ISSUE TITLE
Read Receipt work?

### ISSUE THREAD

**Issue by famewolf** [notpushkin/Mailspring-Libre#41]
Apologies for using an issue to ask this.  I'm not so worried about creating an account especially since I did before finding this.  While I don't need to use more than 4 accounts and don't currently have a need for the "send later" feature I do regularly want to know when an email is opened.   Is this feature available in this version?  I can't see why it would be a "server side" function since typically it's just adding a webbug to the email which gets triggered when the email is loaded.  Thanks for your time!

Also you are on v1.7.2 while the main mailspring is on 1.7.8.   Do they correspond?

**Comment by exprez135** [comment]
Hello! Thank you for writing with your questions. First, we've just released a new version 1.7.8-libre. It's been updated from the main mailspring!

The "read receipts" included in Mailspring are actually a misnomer. A true email-based read-receipt is created by the client adding a proper header to the email file, like "Return-Receipt-To: <email>". Then, your recipient can choose to send back a read receipt (if their client supports it).

Mailspring's read receipts are simply tracking pixels, which load when someone loads your email and contact their servers to notify you. We will not be implementing any version of this because it does not align with our philosophy and requires someone to run a server. The server has to create the end points to track the loading of the webbugs and then associate that with your account and your specific email. It is best to simply ask for someone to reply when they've seen your email.

If you **are** interested in true read receipts, let us know and we can keep that in mind. But that's likely to be a feature which should be implemented upstream before it's done here.

**Comment by AlphetaCS** [comment]
@exprez135 - first I want to say thank you for the recent work you've done; it's nice to see some movement on this project.

My primary concern with the upstream project was that I didn't have any control over how the server would use the data and there was no way to opt out of anything. I'd love to see a switch that could enable a server side piece that we could install / create on our own server to recreate the tracking functionality. Something like an API spec with end-points mailspring-libre could call would be pretty cool.

It's a heavy lift and I understand if it's not something that can be included. Just wanted to put this out there.
