### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [notpushkin/Mailspring-Libre#53]
I use arch linux and I wonder if there an AUR package? I saw an old issue about it but aur link leads to a 404 page

**Comment by notpushkin** [comment]
Hey! Mailspring Libre build is not supported anymore, since the upstream is now fully free and doesn't depend on the Mailspring ID server. There's an AUR package at [mailspring](https://aur.archlinux.org/packages/mailspring) now, and it seems to be regularly updated, so that's what you'll likely want to install.

**Comment by EsmailELBoBDev2** [comment]
oh I thought it's like VScode and VScodium thing. when both are foss but one with telemetry and other is not


Gotcha, thanks!
